### ISSUE TITLE
您好，我想请问如何训练自己的数据集呢？

### ISSUE THREAD

**Issue by px6927** [liyuqing1/PKG-Bert#1]
运行的时候发现buling.wudaoai.cn这个网站已经停用，请问该怎么办？

**Comment by liyuqing1** [comment]
您好，遵照BriVL官方指示：https://github.com/chuhaojin/WenLan-api-document
可以本地部署BriVL模型编码图片/文本，来替代停止运行的在线BriVL api。

**Comment by px6927** [comment]
> 您好，遵照BriVL官方指示：https://github.com/chuhaojin/WenLan-api-document 可以本地部署BriVL模型编码图片/文本，来替代停止运行的在线BriVL api。

好的谢谢您的答复！如果想训练自己的数据集，是不是将节点和边的JSON文件按照格式换成自己的，重新训练就可以了？
